import { DatabaseService } from '../db/database';

const DEFAULT_SETTINGS = {
  clinic: {
    name: '',
    logo: '',
    phone: '',
    altPhone: '',
    email: '',
    website: '',
    address: '',
    city: '',
    postalCode: '',
    country: '',
    registration: '',
    taxId: '',
    currency: 'BDT',
    currencySymbol: '৳',
    invoicePrefix: 'INV',
    receiptPrefix: 'RCP'
  },
  dentist: {
    name: '',
    title: 'Dr.',
    degree: '',
    registrationNumber: '',
    specialization: '',
    phone: '',
    email: '',
    signature: ''
  },
  operational: {
    workingDays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu'],
    openingTime: '09:00',
    closingTime: '20:00',
    appointmentDuration: 30,
    followUpDuration: 30,
    language: 'en',
    dateFormat: 'DD MMM YYYY',
    timeFormat: 'HH:mm',
    numberFormat: 'en-IN'
  },
  invoice: {
    showLogo: true,
    showDentist: true,
    showRegistration: true,
    showSignature: true,
    footerNote: 'This invoice is generated by Dentiva.',
    defaultTerms: 'Payment due within 30 days.',
    taxEnabled: false,
    taxRate: 0
  },
  receipt: {
    showLogo: true,
    footerNote: 'Thank you for your payment.',
    showSignature: true
  },
  printing: {
    defaultPrinter: '',
    paperSize: 'A4',
    orientation: 'portrait',
    margin: 10
  },
  branding: {
    primaryColor: '#0e6b6f',
    accentColor: '#b58a4a',
    footerText: ''
  },
  security: {
    pinEnabled: false,
    pin: '',
    autoLockMinutes: 0
  }
};

export class SettingsService {
  constructor(private db: DatabaseService) {}

  private defaults() {
    return JSON.parse(JSON.stringify(DEFAULT_SETTINGS));
  }

  get() {
    const rows = this.db.all<{key: string; value: string}>('SELECT key, value FROM settings');
    const stored: Record<string, any> = {};
    for (const r of rows) {
      try { stored[r.key] = JSON.parse(r.value); } catch { stored[r.key] = r.value; }
    }
    const merged = this.defaults();
    for (const k of Object.keys(stored)) {
      if (typeof merged[k] === 'object' && merged[k] !== null && !Array.isArray(merged[k])) {
        merged[k] = { ...merged[k], ...stored[k] };
      } else {
        merged[k] = stored[k];
      }
    }
    return merged;
  }

  update(patch: Record<string, any>) {
    const current = this.get();
    const merged = { ...current, ...patch };
    for (const [key, value] of Object.entries(merged)) {
      this.db.run(
        'INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value',
        [key, JSON.stringify(value)]
      );
    }
    return this.get();
  }

  isFirstRun(): boolean {
    const s = this.get();
    return !s.clinic?.name;
  }

  completeSetup(data: any) {
    this.update({
      clinic: data.clinic,
      dentist: data.dentist,
      operational: data.operational,
      completedAt: new Date().toISOString()
    });
  }

  reset() {
    this.db.run('DELETE FROM settings');
    return this.defaults();
  }
}